CREATE TABLE "aluno" (
  "cpf" varchar(11) PRIMARY KEY,
  "nome" varchar(70),
  "genero" char,
  "data_nasc" date,
  "email" varchar(100)
);

CREATE TABLE "matricula" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "data_matricula" date,
  "valor" decimal(10,2),
  "cpf_aluno" varchar(11),
  "id_transacao" integer,
  "id_turma" integer
);

CREATE TABLE "turma" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "qtd_aulas_semanais" integer,
  "horario_inicio" time,
  "horario_fim" time,
  "tamanho" integer,
  "genero" char,
  "nivel" varchar(20),
  "id_modalidade" integer,
  "cpf_instrutor" varchar(11)
);

CREATE TABLE "sala" (
  "numero" integer PRIMARY KEY,
  "title" varchar,
  "capacidade" integer
);

CREATE TABLE "campeonato" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "data" timestamp,
  "sala" integer,
  "categoria" varchar,
  "premiacao" varchar,
  "valor_premiacao" float,
  "status" varchar
);

CREATE TABLE "inscricao" (
  "numero_insc" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "taxa" decimal(10,2),
  "data_insc" date,
  "id_transacao" integer,
  "id_campeonato" integer,
  "cpf_aluno" varchar(11)
);

CREATE TABLE "transacao_entrada" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "valor" decimal(10,2),
  "data_hora" timestamp,
  "descricao" varchar(255),
  "emissor" varchar(70),
  "id_nota_fiscal" varchar
);

CREATE TABLE "transacao_saida" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "valor" decimal(10,2),
  "data_hora" timestamp,
  "descricao" varchar(255),
  "receptor" varchar(70),
  "id_nota_fiscal" varchar
);

CREATE TABLE "pagamentos" (
  "id_transacao" integer PRIMARY KEY,
  "cpf_func" varchar(11)
);

CREATE TABLE "funcionario" (
  "cpf" varchar(11) PRIMARY KEY,
  "nome" varchar(70),
  "genero" char,
  "data_admissao" date,
  "cargo" varchar,
  "salario" decimal(10,2),
  "email" varchar(100),
  "cep" varchar(8),
  "numero" int,
  "complemento" varchar(100),
  "cpf_adm" varchar(11)
);

CREATE TABLE "instrutor" (
  "cpf" varchar(11) PRIMARY KEY
);

CREATE TABLE "administrativo" (
  "cpf" varchar(11) PRIMARY KEY,
  "nivel_acessos" integer
);

CREATE TABLE "equipamentos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar(255)
);

CREATE TABLE "modalidade" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100)
);

CREATE TABLE "turma_sala" (
  "id_locacao" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_turma" integer,
  "id_sala" integer,
  "inicio_locacao" date,
  "fim_locacao" date
);

CREATE TABLE "sala_equipamento" (
  "id_equipamento" integer,
  "id_sala" integer,
  "quantidade" integer,
  PRIMARY KEY ("id_equipamento", "id_sala")
);

CREATE TABLE "sala_modalidade" (
  "id_sala" integer,
  "id_modalidade" integer,
  PRIMARY KEY ("id_sala", "id_modalidade")
);

CREATE TABLE "instrutor_modalidade" (
  "cpf_instrutor" varchar(11),
  "id_modalidade" integer,
  "nivel_capacitacao" integer,
  PRIMARY KEY ("cpf_instrutor", "id_modalidade")
);

ALTER TABLE "matricula" ADD FOREIGN KEY ("cpf_aluno") REFERENCES "aluno" ("cpf");

ALTER TABLE "matricula" ADD FOREIGN KEY ("id_turma") REFERENCES "turma" ("id");

ALTER TABLE "funcionario" ADD FOREIGN KEY ("cpf_adm") REFERENCES "administrativo" ("cpf");

ALTER TABLE "inscricao" ADD FOREIGN KEY ("id_campeonato") REFERENCES "campeonato" ("id");

ALTER TABLE "campeonato" ADD FOREIGN KEY ("sala") REFERENCES "sala" ("numero");

ALTER TABLE "turma" ADD FOREIGN KEY ("id_modalidade") REFERENCES "modalidade" ("id");

ALTER TABLE "turma" ADD FOREIGN KEY ("cpf_instrutor") REFERENCES "instrutor" ("cpf");

ALTER TABLE "inscricao" ADD FOREIGN KEY ("cpf_aluno") REFERENCES "aluno" ("cpf");

ALTER TABLE "pagamentos" ADD FOREIGN KEY ("cpf_func") REFERENCES "funcionario" ("cpf");

ALTER TABLE "pagamentos" ADD FOREIGN KEY ("id_transacao") REFERENCES "transacao_saida" ("id");

ALTER TABLE "instrutor" ADD FOREIGN KEY ("cpf") REFERENCES "funcionario" ("cpf");

ALTER TABLE "administrativo" ADD FOREIGN KEY ("cpf") REFERENCES "funcionario" ("cpf");

ALTER TABLE "inscricao" ADD FOREIGN KEY ("id_transacao") REFERENCES "transacao_entrada" ("id");

ALTER TABLE "matricula" ADD FOREIGN KEY ("id_transacao") REFERENCES "transacao_entrada" ("id");

ALTER TABLE "turma_sala" ADD FOREIGN KEY ("id_turma") REFERENCES "turma" ("id");

ALTER TABLE "turma_sala" ADD FOREIGN KEY ("id_sala") REFERENCES "sala" ("numero");

ALTER TABLE "sala_equipamento" ADD FOREIGN KEY ("id_equipamento") REFERENCES "equipamentos" ("id");

ALTER TABLE "sala_equipamento" ADD FOREIGN KEY ("id_sala") REFERENCES "sala" ("numero");

ALTER TABLE "sala_modalidade" ADD FOREIGN KEY ("id_sala") REFERENCES "sala" ("numero");

ALTER TABLE "sala_modalidade" ADD FOREIGN KEY ("id_modalidade") REFERENCES "modalidade" ("id");

ALTER TABLE "instrutor_modalidade" ADD FOREIGN KEY ("cpf_instrutor") REFERENCES "instrutor" ("cpf");

ALTER TABLE "instrutor_modalidade" ADD FOREIGN KEY ("id_modalidade") REFERENCES "modalidade" ("id");


CREATE INDEX idx_aluno_email ON aluno(email);

CREATE INDEX idx_matricula_cpf_aluno ON matricula(cpf_aluno);

CREATE INDEX idx_funcionario_data_admissao ON funcionario(data_admissao);
